### ISSUE TITLE
Path in deployed CTFE public key file for ephemeral TUF creation should include "ctfe" to correctly hint as to its use in TUF creation

### ISSUE THREAD

**Issue by LewisThomas** [sigstore/helm-charts#670]
https://github.com/sigstore/helm-charts/blob/b3876089c778987b29a89cee6ec14c6fd3679336/charts/scaffold/values.yaml#L82C16-L82C16

needs to be called CTFE instead of ctlog.

As per here:

https://github.com/sigstore/scaffolding/blob/2be6921bb64c02ec00e65c69b3dc41191df5f5cd/pkg/repo/repo.go#L137C11-L137C11

Slack Thread + GitHub issue likely related:
https://github.com/sigstore/cosign/issues/3386
https://sigstore.slack.com/archives/C01PZKDL4DP/p1700838479395349?thread_ts=1694462110.654769&cid=C01PZKDL4DP

**Comment by federico-falconieri-form3** [comment]
@LewisThomas I also reported this here https://github.com/sigstore/scaffolding/issues/873

**Comment by haydentherapper** [comment]
https://github.com/sigstore/helm-charts/pull/673 should fix this using the fallback names. Can you confirm this?

**Comment by federico-falconieri-form3** [comment]
> #673 should fix this using the fallback names. Can you confirm this?

@haydentherapper I can confirm #673 fixes this.

However #673 did not update the default values of the scaffold chart, so the bug is still present when one does not override them. I've opened #679
